-- V1 

CREATE Table users (
	id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL PRIMARY KEY,
	fullName varchar2(255),
	username varchar2(255) NOT NULL,
	password varchar2(255) NOT NULL
);


-- V2

INSERT INTO USERS values (1, 'Ahmed Sameh', 0100000000, 'Egypt, Giza', 'dev.ahmedsameh76@gmail.com', 'u79032D&*&');


CREATE Table users (
	id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL PRIMARY KEY,
	fullName varchar2(255) NOT NULL,
	phoneNumber NUMBER,
	address varchar2(255),
	email varchar2(255) NOT NULL,
	password varchar2(255) NOT NULL
);